spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://request-db:5432/ewm-request
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false

  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          JpaTransactionManager: INFO
        transaction:
          interceptor: INFO
