spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://stats-db:5432/ewm-stats
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          JpaTransactionManager: INFO
        transaction:
          interceptor: INFO

resilience4j.circuitbreaker:
  instances:
    myService:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000 # 10 секунд в миллисекундах
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
